"""
Traducción al español de las etiquetas de AudioSet (527 clases) usadas por PANNs.

No se traducen las 527: se cubren las categorías de sonido más comunes (voz,
música, instrumentos, vehículos/motores, naturaleza, animales, hogar, alarmas,
ruido…). Para cualquier etiqueta no listada se devuelve el nombre en inglés tal
cual (fallback), de modo que la UI siempre muestra algo legible.

La clave del diccionario es el `display_name` EXACTO del CSV de AudioSet.
"""
from __future__ import annotations

# display_name (inglés, tal cual en class_labels_indices.csv) -> español
LABELS_ES: dict[str, str] = {
    # --- Voz / habla humana ---
    "Speech": "Voz humana",
    "Male speech, man speaking": "Voz masculina",
    "Female speech, woman speaking": "Voz femenina",
    "Child speech, kid speaking": "Voz de niño",
    "Conversation": "Conversación",
    "Narration, monologue": "Narración / monólogo",
    "Babbling": "Balbuceo",
    "Speech synthesizer": "Voz sintética",
    "Shout": "Grito",
    "Bellow": "Bramido",
    "Whoop": "Aullido de júbilo",
    "Yell": "Alarido",
    "Children shouting": "Niños gritando",
    "Screaming": "Chillidos",
    "Whispering": "Susurros",
    "Laughter": "Risas",
    "Baby laughter": "Risa de bebé",
    "Giggle": "Risita",
    "Snicker": "Risa disimulada",
    "Belly laugh": "Carcajada",
    "Chuckle, chortle": "Risa entre dientes",
    "Crying, sobbing": "Llanto / sollozos",
    "Baby cry, infant cry": "Llanto de bebé",
    "Whimper": "Gimoteo",
    "Wail, moan": "Lamento / quejido",
    "Sigh": "Suspiro",
    "Singing": "Canto",
    "Choir": "Coro",
    "Yodeling": "Canto tirolés",
    "Chant": "Cántico",
    "Mantra": "Mantra",
    "Male singing": "Canto masculino",
    "Female singing": "Canto femenino",
    "Child singing": "Canto infantil",
    "Synthetic singing": "Canto sintético",
    "Rapping": "Rap",
    "Humming": "Tarareo",
    "Groan": "Gruñido humano",
    "Grunt": "Resoplido",
    "Whistling": "Silbido",
    "Breathing": "Respiración",
    "Wheeze": "Respiración sibilante",
    "Snoring": "Ronquidos",
    "Gasp": "Jadeo brusco",
    "Pant": "Jadeo",
    "Cough": "Tos",
    "Throat clearing": "Carraspeo",
    "Sneeze": "Estornudo",
    "Sniff": "Sorbido nasal",
    "Walk, footsteps": "Pasos",
    "Run": "Correr",
    "Chewing, mastication": "Masticación",
    "Burping, eructation": "Eructo",
    "Hiccup": "Hipo",

    # --- Manos / público ---
    "Hands": "Manos",
    "Finger snapping": "Chasquido de dedos",
    "Clapping": "Palmas",
    "Cheering": "Vítores",
    "Applause": "Aplausos",
    "Chatter": "Murmullo de gente",
    "Crowd": "Multitud",
    "Hubbub, speech noise, speech babble": "Bullicio de voces",
    "Children playing": "Niños jugando",

    # --- Animales ---
    "Animal": "Animal",
    "Domestic animals, pets": "Animales domésticos",
    "Dog": "Perro",
    "Bark": "Ladrido",
    "Howl": "Aullido",
    "Growling": "Gruñido",
    "Cat": "Gato",
    "Purr": "Ronroneo",
    "Meow": "Maullido",
    "Hiss": "Bufido",
    "Horse": "Caballo",
    "Cattle, bovinae": "Ganado vacuno",
    "Moo": "Mugido",
    "Pig": "Cerdo",
    "Goat": "Cabra",
    "Sheep": "Oveja",
    "Fowl": "Aves de corral",
    "Chicken, rooster": "Gallo / gallina",
    "Duck": "Pato",
    "Bird": "Ave",
    "Bird vocalization, bird call, bird song": "Canto de pájaros",
    "Chirp, tweet": "Trino",
    "Crow": "Cuervo",
    "Owl": "Búho",
    "Insect": "Insecto",
    "Cricket": "Grillo",
    "Mosquito": "Mosquito",
    "Fly, housefly": "Mosca",
    "Buzz": "Zumbido",
    "Bee, wasp, etc.": "Abeja / avispa",
    "Frog": "Rana",

    # --- Música / instrumentos ---
    "Music": "Música",
    "Musical instrument": "Instrumento musical",
    "Plucked string instrument": "Instrumento de cuerda pulsada",
    "Guitar": "Guitarra",
    "Electric guitar": "Guitarra eléctrica",
    "Bass guitar": "Bajo eléctrico",
    "Acoustic guitar": "Guitarra acústica",
    "Banjo": "Banjo",
    "Ukulele": "Ukelele",
    "Keyboard (musical)": "Teclado musical",
    "Piano": "Piano",
    "Electric piano": "Piano eléctrico",
    "Organ": "Órgano",
    "Synthesizer": "Sintetizador",
    "Percussion": "Percusión",
    "Drum kit": "Batería",
    "Drum": "Tambor",
    "Snare drum": "Caja",
    "Bass drum": "Bombo",
    "Cymbal": "Platillo",
    "Hi-hat": "Charles (hi-hat)",
    "Tambourine": "Pandereta",
    "Brass instrument": "Instrumento de metal",
    "Trumpet": "Trompeta",
    "Trombone": "Trombón",
    "Saxophone": "Saxofón",
    "Violin, fiddle": "Violín",
    "Cello": "Violonchelo",
    "Flute": "Flauta",
    "Harmonica": "Armónica",
    "Accordion": "Acordeón",
    "Bell": "Campana",
    "Church bell": "Campana de iglesia",
    "Wind instrument, woodwind instrument": "Instrumento de viento",
    "String section": "Sección de cuerdas",
    "Pop music": "Música pop",
    "Rock music": "Música rock",
    "Hip hop music": "Música hip hop",
    "Classical music": "Música clásica",
    "Electronic music": "Música electrónica",
    "Jazz": "Jazz",
    "Reggae": "Reggae",
    "Country": "Música country",
    "Folk music": "Música folk",
    "Ambient music": "Música ambiental",
    "Christmas music": "Música navideña",
    "Background music": "Música de fondo",
    "Theme music": "Música de cabecera",
    "Soundtrack music": "Banda sonora",
    "Jingle (music)": "Sintonía / jingle",

    # --- Naturaleza / clima / agua ---
    "Wind": "Viento",
    "Rustling leaves": "Hojas moviéndose",
    "Wind noise (microphone)": "Ruido de viento (micrófono)",
    "Thunderstorm": "Tormenta",
    "Thunder": "Trueno",
    "Water": "Agua",
    "Rain": "Lluvia",
    "Raindrop": "Gotas de lluvia",
    "Rain on surface": "Lluvia sobre superficie",
    "Stream": "Arroyo",
    "Waterfall": "Cascada",
    "Ocean": "Mar",
    "Waves, surf": "Olas",
    "Fire": "Fuego",
    "Crackle": "Crepitar",

    # --- Vehículos / motores ---
    "Vehicle": "Vehículo",
    "Boat, Water vehicle": "Embarcación",
    "Motorboat, speedboat": "Lancha motora",
    "Ship": "Barco",
    "Motor vehicle (road)": "Vehículo de motor",
    "Car": "Coche",
    "Vehicle horn, car horn, honking": "Bocina",
    "Car alarm": "Alarma de coche",
    "Car passing by": "Coche pasando",
    "Truck": "Camión",
    "Bus": "Autobús",
    "Emergency vehicle": "Vehículo de emergencia",
    "Police car (siren)": "Coche de policía (sirena)",
    "Ambulance (siren)": "Ambulancia (sirena)",
    "Fire engine, fire truck (siren)": "Camión de bomberos (sirena)",
    "Motorcycle": "Motocicleta",
    "Traffic noise, roadway noise": "Ruido de tráfico",
    "Train": "Tren",
    "Subway, metro, underground": "Metro",
    "Aircraft": "Aeronave",
    "Aircraft engine": "Motor de avión",
    "Jet engine": "Motor a reacción",
    "Helicopter": "Helicóptero",
    "Fixed-wing aircraft, airplane": "Avión",
    "Bicycle": "Bicicleta",
    "Engine": "Motor",
    "Light engine (high frequency)": "Motor ligero",
    "Lawn mower": "Cortacésped",
    "Chainsaw": "Motosierra",
    "Medium engine (mid frequency)": "Motor mediano",
    "Heavy engine (low frequency)": "Motor pesado",
    "Engine starting": "Arranque de motor",
    "Idling": "Motor al ralentí",
    "Accelerating, revving, vroom": "Acelerón",

    # --- Hogar / objetos ---
    "Door": "Puerta",
    "Doorbell": "Timbre",
    "Sliding door": "Puerta corredera",
    "Slam": "Portazo",
    "Knock": "Golpes en puerta",
    "Tap": "Golpecito",
    "Squeak": "Chirrido",
    "Dishes, pots, and pans": "Vajilla y cacerolas",
    "Cutlery, silverware": "Cubertería",
    "Frying (food)": "Fritura",
    "Microwave oven": "Microondas",
    "Water tap, faucet": "Grifo",
    "Toilet flush": "Cisterna",
    "Vacuum cleaner": "Aspiradora",
    "Keys jangling": "Llaves tintineando",
    "Typing": "Tecleo",
    "Computer keyboard": "Teclado de ordenador",
    "Writing": "Escritura",

    # --- Alarmas / timbres / teléfono ---
    "Alarm": "Alarma",
    "Telephone": "Teléfono",
    "Telephone bell ringing": "Timbre de teléfono",
    "Ringtone": "Tono de llamada",
    "Alarm clock": "Despertador",
    "Siren": "Sirena",
    "Buzzer": "Zumbador",
    "Smoke detector, smoke alarm": "Detector de humo",
    "Fire alarm": "Alarma de incendios",
    "Whistle": "Silbato",
    "Beep, bleep": "Pitido",
    "Bell": "Campana",

    # --- Máquinas / herramientas / impactos ---
    "Mechanisms": "Mecanismos",
    "Clock": "Reloj",
    "Tick": "Tic",
    "Tick-tock": "Tictac",
    "Mechanical fan": "Ventilador mecánico",
    "Air conditioning": "Aire acondicionado",
    "Printer": "Impresora",
    "Camera": "Cámara",
    "Tools": "Herramientas",
    "Hammer": "Martillo",
    "Jackhammer": "Martillo neumático",
    "Sawing": "Serrado",
    "Power tool": "Herramienta eléctrica",
    "Drill": "Taladro",
    "Explosion": "Explosión",
    "Gunshot, gunfire": "Disparo",
    "Fireworks": "Fuegos artificiales",
    "Firecracker": "Petardo",
    "Boom": "Estruendo",
    "Glass": "Cristal",
    "Shatter": "Cristal rompiéndose",
    "Breaking": "Rotura",
    "Bang": "Golpe seco",
    "Clang": "Clanc metálico",
    "Rumble": "Retumbo",

    # --- Ruido / entorno / ambiente ---
    "Silence": "Silencio",
    "Inside, small room": "Interior, sala pequeña",
    "Inside, large room or hall": "Interior, sala grande",
    "Inside, public space": "Interior, espacio público",
    "Outside, urban or manmade": "Exterior urbano",
    "Outside, rural or natural": "Exterior rural / natural",
    "Reverberation": "Reverberación",
    "Echo": "Eco",
    "Noise": "Ruido",
    "Environmental noise": "Ruido ambiental",
    "Static": "Estática",
    "Mains hum": "Zumbido eléctrico (red)",
    "Distortion": "Distorsión",
    "Cacophony": "Cacofonía",
    "White noise": "Ruido blanco",
    "Pink noise": "Ruido rosa",
    "Hum": "Zumbido",
    "Vibration": "Vibración",
    "Television": "Televisión",
    "Radio": "Radio",
    "Field recording": "Grabación de campo",
}


def to_spanish(display_name: str) -> str:
    """Devuelve la traducción al español si existe; si no, el nombre original."""
    return LABELS_ES.get(display_name, display_name)
